### PR TITLE
Added ppc64le support

### PR DESCRIPTION
**Pull request by artemry-mlnx**
Signed-off-by: Artem Ryabov <artemry@mellanox.com>

### CODE REVIEW

**Comment by artemry-mlnx** [comment]
@mike-dubman for some reasons I cannot add reviewers - could you please grant me permissions?

**Comment by mike-dubman** [comment]
> @mike-dubman for some reasons I cannot add reviewers - could you please grant me permissions?

plz try now

**Comment by artemry-mlnx** [comment]
> > @mike-dubman for some reasons I cannot add reviewers - could you please grant me permissions?
> 
> plz try now

Still not available.

**Review by mike-dubman — APPROVED** [review]

**Comment by mike-dubman** [comment]
> > > @mike-dubman for some reasons I cannot add reviewers - could you please grant me permissions?
> > 
> > 
> > plz try now
> 
> Still not available.

and now?

**Comment by artemry-mlnx** [comment]
> > > > @mike-dubman for some reasons I cannot add reviewers - could you please grant me permissions?
> > > 
> > > 
> > > plz try now
> > 
> > 
> > Still not available.
> 
> and now?

Thanks, works fine for me. Can we also add others (now I cannot add other teammates as reviewers)? 
CC @MrBr-github (it seems you've created a group for us, haven't you?)

**Comment by artemry-mlnx** [comment]
CC @vasily-v-ryabov @aod314

**Comment by mike-dubman** [comment]
> > > > > @mike-dubman for some reasons I cannot add reviewers - could you please grant me permissions?
> > > > 
> > > > 
> > > > plz try now
> > > 
> > > 
> > > Still not available.
> > 
> > 
> > and now?
> 
> Thanks, works fine for me. Can we also add others (now I cannot add other teammates as reviewers)?
> CC @MrBr-github (it seems you've created a group for us, haven't you?)
> 
> UPD: cannot add only Andrey and Vasily.

you have full admin rights on this repo - plz add more folks as needed.
Also, you can create github group with all and add group only.

**Review by vasily-v-ryabov — APPROVED** [review]

**Pull request merged**
